# Generated by Django 5.0.6 on 2026-04-09 15:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0002_comment_videorating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Video Comment'},
        ),
        migrations.AlterModelOptions(
            name='videorating',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Video Rating'},
        ),
        migrations.AlterModelOptions(
            name='wellnessrating',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Wellness Rating (legacy)'},
        ),
        migrations.AddField(
            model_name='videorating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='video_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='videorating',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')]),
        ),
        migrations.AlterField(
            model_name='videorating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videorating',
            name='video_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='wellnessrating',
            name='emotion_selected',
            field=models.CharField(choices=[('angry', 'Angry'), ('anxious', 'Anxious'), ('stressed', 'Stressed'), ('restless', 'Restless')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wellnessrating',
            name='rating_score',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='wellnessrating',
            name='session_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='wellnessrating',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wellnessrating',
            name='video_ids',
            field=models.TextField(blank=True),
        ),
    ]
