# Generated by Django 5.0.6 on 2026-04-17 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0006_watch_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchhistory',
            name='watched_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
